// Renders the Homebrew formula for one release from its checksums.txt, so the
// tap (colevels/homebrew-tap) is an output of this repo and never edited by hand.
//
//   bun scripts/homebrew-formula.ts <version> <checksums.txt> > tabbrew.rb
import { readFileSync } from 'node:fs'

const REPOSITORY = 'colevels/tabbrew-cli'
const STORE_URL = 'https://chromewebstore.google.com/detail/ikmpmkkcmhhnjmdiooekbhfmomcbefkf'

const TARGETS = [
  ['darwin', 'arm64'],
  ['darwin', 'x64'],
  ['linux', 'arm64'],
  ['linux', 'x64'],
] as const

export type Checksums = Record<string, string>

// One "<sha256>  <asset>" per line, as shasum writes it.
export function parseChecksums(text: string): Checksums {
  const checksums: Checksums = {}
  for (const line of text.split('\n')) {
    const [sha, asset] = line.trim().split(/\s+/)
    if (sha && asset) checksums[asset] = sha
  }
  return checksums
}

export function renderFormula(version: string, checksums: Checksums): string {
  const missing = TARGETS.map(([os, cpu]) => `tabbrew-${os}-${cpu}`).filter(
    (asset) => !/^[0-9a-f]{64}$/.test(checksums[asset] ?? ''),
  )
  if (missing.length > 0) throw new Error(`no sha256 for ${missing.join(', ')}`)

  const block = (os: 'darwin' | 'linux') =>
    ['arm', 'intel']
      .map((cpuBlock, i) => {
        const cpu = i === 0 ? 'arm64' : 'x64'
        const asset = `tabbrew-${os}-${cpu}`
        return [
          `    on_${cpuBlock} do`,
          `      url "https://github.com/${REPOSITORY}/releases/download/v${version}/${asset}"`,
          `      sha256 "${checksums[asset]}"`,
          '    end',
        ].join('\n')
      })
      .join('\n')

  return `# Generated by scripts/homebrew-formula.ts in ${REPOSITORY}; do not edit by hand.
class Tabbrew < Formula
  desc "Manage Chrome tabs, windows and tab groups from the terminal"
  homepage "https://github.com/${REPOSITORY}"
  license "MIT"

  on_macos do
${block('darwin')}
  end

  on_linux do
${block('linux')}
  end

  def install
    bin.install Dir["tabbrew-*"].first => "tabbrew"
  end

  def caveats
    <<~EOS
      Install the TabBrew extension from the Chrome Web Store:
        ${STORE_URL}
      Then: tabbrew session start

      Upgrade with \`brew upgrade tabbrew\`; \`tabbrew update\` refuses Homebrew installs.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tabbrew --version")
  end
end
`
}

if (import.meta.main) {
  const [version, checksumsPath] = process.argv.slice(2)
  if (!version || !checksumsPath) {
    console.error('usage: homebrew-formula.ts <version> <checksums.txt>')
    process.exit(2)
  }
  process.stdout.write(
    renderFormula(version.replace(/^v/, ''), parseChecksums(readFileSync(checksumsPath, 'utf8'))),
  )
}
